version: 2.1
orbs:
  cypress: cypress-io/cypress@13
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
      
           start-command: npx vite preview
           cypress-command: npx cypress run --component

