version: 2.1
orbs:
  cypress: cypress-io/cypress@13
workflows:
  test:
    jobs:
      - cypress/run:
           install-browsers: true
           start-command: 'npx vite preview'
           cypress-command: 'npx cypress run --component --browser chrome'

